language: ruby
rvm:
  - 2.0.0-p247

before_install:

install:
        - npm install -g grunt-cli
        - npm install -g bower

before_script:
        - npm install -g casperjs
        - phantomjs --version; casperjs --version; bower --version
        - cd ./uidu
        - bundle install
        - bower install
        - ls
        - sleep 5
        - RAILS_ENV=test bundle exec rake --trace db:migrate test
        - ./script/rails server &
        - sleep 5

script: ./runTests.sh
