language: ruby
rvm:
  - 2.0.0-p247

before_install:

install:
        - npm install -g grunt-cli

before_script:
        - npm install
        - cd ./uidu
        - bundle install
        - bower install
        - RAILS_ENV=test bundle exec rake --trace db:migrate test
        - ./script/rails server &
        - sleep 5

script: ./runTests.sh
