language: node_js

node_js:
        - 0.10

before_install:

install:
        - npm install -g grunt-cli

before_script:
        - npm install -g casperjs
        - phantomjs --version; casperjs --version
        - cd ./uidu
        -  ./script/rails server

script: ./runTests.sh
